services:
    dizda.Backup.database.mongodb:
        class: Dizda\BackupBundle\Databases\MongoDB
        arguments:
            - %dizda_cloud_backup.databases.mongodb.all_databases%
            - %dizda_cloud_backup.databases.mongodb.host%
            - %dizda_cloud_backup.databases.mongodb.port%
            - %dizda_cloud_backup.databases.mongodb.database%
            - %dizda_cloud_backup.databases.mongodb.db_user%
            - %dizda_cloud_backup.databases.mongodb.db_password%
            - %dizda_cloud_backup.output_file_prefix%
        calls:
            - [setKernelCacheDir, ["%kernel.cache_dir%"]]

    dizda.Backup.database.mysql:
        class: Dizda\BackupBundle\Databases\MySQL
        arguments:
            - %dizda_cloud_backup.databases.mysql.all_databases%
            - %dizda_cloud_backup.databases.mysql.host%
            - %dizda_cloud_backup.databases.mysql.port%
            - %dizda_cloud_backup.databases.mysql.database%
            - %dizda_cloud_backup.databases.mysql.db_user%
            - %dizda_cloud_backup.databases.mysql.db_password%
            - %dizda_cloud_backup.output_file_prefix%
        calls:
            - [setKernelCacheDir, ["%kernel.cache_dir%"]]

    dizda.Backup.database.postgresql:
        class: Dizda\BackupBundle\Databases\PostgreSQL
        arguments:
            - %dizda_cloud_backup.databases.postgresql.host%
            - %dizda_cloud_backup.databases.postgresql.port%
            - %dizda_cloud_backup.databases.postgresql.database%
            - %dizda_cloud_backup.databases.postgresql.db_user%
            - %dizda_cloud_backup.databases.postgresql.db_password%
            - %dizda_cloud_backup.output_file_prefix%
        calls:
            - [setKernelCacheDir, ["%kernel.cache_dir%"]]
